spring.application.name=dulcearte
spring.datasource.url=jdbc:postgresql://localhost:5432/DulceArte
spring.datasource.username=dulcearte
spring.datasource.password=dulce
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# (Opcional) puerto del servidor
server.port=8080
